name: build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        ruby: [2.7.2, 3.4.4]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake
